Explicitly set output of aws cli to json
awslabs/karpenter pull request #407
Opened 2021-05-18 09:50 UTC by pjlewisuk

**Description of changes:**
 When working through the getting started docs I noticed an issue with `aws` commands that were piped to `jq`, and cause an error like:

```
parse error: Invalid numeric literal at line 1, column 8
```

This was because my default output was not set to `json` for the AWS CLI, so added the `--output json` option to the relevant commands.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-18 15:22 UTC, bwagner5 commented
Thanks for bringing this up! Rather than specifying the `--output json` in each command, would you mind adding the environment variable output config at the top of the file in the `Environment` section?  

Putting it there will reduce the amount of bloat in the commands and we won't have to remember to add the output flag on any new aws cli commands we may add to this page.

https://github.com/awslabs/karpenter/blob/c85f7e58ac8d43f6cb542948fd8e72d15cab13ca/docs/aws/README.md#environment 

```
...
export AWS_DEFAULT_OUTPUT="json"
```

2021-05-18 15:23 UTC, bwagner5 requested changes
move aws cli output config to environment block

2021-05-20 10:43 UTC, pjlewisuk commented
@bwagner5 thanks for the feedback, updated as per your suggestion

2021-05-20 15:19 UTC, bwagner5 approved these changes
lgtm! Awesome, thanks for helping to keep our docs clean and correct!

2021-05-20 15:19 UTC, merged